### ISSUE TITLE
录音录视频同时使用异常问题

### ISSUE THREAD

**Issue by wl083** [shaoshuai904/RecordWav#8]
在尝试同时录视频和音频，录音频用的是开源库
https://github.com/MingYueChunQiu/RecorderManager ，在录制音、视频结束释放资源时，抛出 AudioRecord 没有初始化异常：
java.lang.IllegalStateException: stop() called on an uninitialized AudioRecord.
        at android.media.AudioRecord.stop(AudioRecord.java:1173)
        at com.maple.recordvoice.recording.BaseDataRecorder.stopRecording(BaseDataRecorder.java:83)
        at com.maple.recordvoice.recording.WavRecorder.stopRecording(WavRecorder.java:23)

**Comment by shaoshuai904** [comment]
已解决，请使用最新的版本
